### ISSUE TITLE
Schwarz Contact Bug: Static Cube Contact Initial Timestep in Contact

### ISSUE THREAD

**Issue by brianphung** [lxmota/Norma.jl#24] opened 2024-11-19 19:56 UTC
![Screenshot 2024-11-19 at 12 54 58 PM](https://github.com/user-attachments/assets/c0cf1a3d-9e2b-4eed-a8af-347600a2e28f)
At the initial time step, the cubes are in contact with each other. The correct behavior is they should be separated.

**Comment by brianphung** [comment] 2024-11-19 21:52
Bug originates from the applied boundary condition and initial mesh specification. For the problem specified:
![Screenshot 2024-11-19 at 2 44 12 PM](https://github.com/user-attachments/assets/1fbd7ba4-51de-45c5-ba1a-4d55c6455f6e)
Transparent blocks in green and red are the results file at t = -4. The white/grey block is the original input mesh (direct from Cubit). When the boundary condition (ssx+ = 0.3) is applied, it applies it to (ssx+) without moving ssx-. Therefore, the Schwarz controller, seeing that Cube 2's ssx- is in contact with Cube 1's ssx+, detects contact for the first time step.

This problem is reproduced when we move the original input mesh blocks such that the blocks are not initially in contact:
![Screenshot 2024-11-19 at 2 50 24 PM](https://github.com/user-attachments/assets/5812cc32-414f-401b-bc7b-82c7e4e070c0)

In this modified example, original Cubit meshes are moved 0.3 units away from each other. In other words, the original meshes are not in contact like in the previous example. The green and red blocks are at t=-4. Like above, the exterior x-side-sets have their boundary conditions applied (i.e., an addition 0.3 units away from each other), while the interior x-side-sets are not also moved, resulting in stretched blocks for the initial time step.

**Comment by lxmota** [comment] 2024-11-19 23:00
Yes, and I know what the problem is. I had a feature called initial equilibrium for quasistatic problems that I removed because it was interfering with calculations in another project. I could change the boundary condition but I think what I'm going to do is to reintroduce that feature again and make it optional, being disabled by default.

**Comment by lxmota** [comment] 2024-11-19 23:26
Fixed by cdc2e96c29cef9a8e045caf7f1f9fd0bf5d33789

**Closed by lxmota** 2024-11-19 23:26 UTC
Labels: bug
